#ifndef AUTOSAR_TYPE_DEFINES
#define AUTOSAR_TYPE_DEFINES

#define APPLICATION_SW_COMPONENT_TYPE "APPLICATION-SW-COMPONENT-TYPE"
#define AR_PACKAGE "AR-PACKAGE"
#define AR_PACKAGES "AR-PACKAGES"
#define AUTOSAR "AUTOSAR"
#define SHORT_NAME "SHORT-NAME"
#endif