#ifndef GUI_IDS
#define GUI_IDS

#define DRAW_PANE_ID 0
#define COMMUNICATION_PANEL_ID 1
#define COMMUNICATION_PANEL_TITLE_ID 2
#define COMMUNICATION_PANEL_LIST_ID 3
#define EMPTY_SPACE_ID 100

#endif